version: '3.5'

services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: forms
    ports:
      - "5432:5432"
    restart: unless-stopped
